# version: "3.2"
name: First app System
#object ke andr ek aur image 
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: zzvariationsafk/firstapp:latest
    ports:
      - "3000:3000"
    volumes:
      - ./:app
      - /app/node_modules
    depends_on:
      - db

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: