# name: some text
# access: true
# course: 
#    -maths
#    -science

# addresses:
#  home_address:
#     house_number: 111
#     Street: 12
#  office_address:
#     house_number: 111
#     Street: 12


name: Docker build and push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - uses: actions/checkout@v4

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Docker Hub Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Build the Docker image
      - name: Build Docker image
        run: docker build -t psdcoder/myfirstapp:v0.0.1 .

      # Push the Docker image to Docker Hub
      - name: Push Docker image
        run: docker push psdcoder/myfirstapp:v0.0.1

