# name: some text
# access: true
# course: 
#    -maths
#    -science

# addresses:
#  home_address:
#     house_number: 111
#     Street: 12
#  office_address:
#     house_number: 111
#     Street: 12



name: Docker build and push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        run: echo "${{ secrets.AreeshaFaisal944 }}" | docker login -u "${{ secrets.ZZVARIATIONSAFK }}" --password-stdin

      - name: Build Docker image
        run: docker build -t zzvariationsafk/firstapp:latest .

      - name: Push Docker image
        run: docker push zzvariationsafk/firstapp:latest
